### ISSUE TITLE
NPE on PVP death

### ISSUE THREAD

**Issue by downslope7** [tterrag1098/CustomThings#1]
```
[18:35:03] [Server thread/INFO]: openblocks.common.PlayerInventoryStore.onPlayerDeath(PlayerInventoryStore.java:195): Storing post-mortem inventory into /home/minecraft/McMyAdmin/Minecraft/./world/data/inventory-prerequisite-2015-03-08_18.35.03-death-0.dat. It can be restored with command '/ob_inventory restore prerequisite prerequisite-2015-03-08_18.35.03-death-0'
[18:35:03] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent@515d7e3a:
java.lang.NullPointerException
    at tterrag.customthings.common.config.json.AchievementType$AchievementSource$4.matchesObject(AchievementType.java:111) ~[AchievementType$AchievementSource$4.class:?]
    at tterrag.customthings.common.handlers.AchievementHandler.onEntityDeath(AchievementHandler.java:48) ~[AchievementHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_627_AchievementHandler_onEntityDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:315) [ForgeHooks.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
    at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:521) [mw.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:979) [sv.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1144) [yz.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:646) [mw.class:?]
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:74) [GCEntityPlayerMP.class:?]
    at tconstruct.library.tools.AbilityHelper.onLeftClickEntity(AbilityHelper.java:125) [AbilityHelper.class:?]
    at tconstruct.library.tools.AbilityHelper.onLeftClickEntity(AbilityHelper.java:56) [AbilityHelper.class:?]
    at tconstruct.items.tools.Cleaver.onLeftClickEntity(Cleaver.java:123) [Cleaver.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1346) [yz.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1589) [nh.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
[18:35:03] [Server thread/ERROR]: Index: 20 Listeners:
[18:35:03] [Server thread/ERROR]: 0: HIGHEST
[18:35:03] [Server thread/ERROR]: 1: ASM: vazkii.botania.common.item.equipment.bauble.ItemGoldenLaurel@a26e7c7 onPlayerDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 2: ASM: erebus.core.handler.EntityDeathEventHandler@4df84f9a deathEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 3: HIGH
[18:35:03] [Server thread/ERROR]: 4: ASM: openblocks.common.PlayerInventoryStore@28523552 onPlayerDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 5: ASM: com.emoniph.witchery.infusion.Infusion$EventHooks@71f13f6 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 6: ASM: com.emoniph.witchery.common.GenericEvents@1feb1270 onLivingDeathEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 7: NORMAL
[18:35:03] [Server thread/ERROR]: 8: ASM: thaumcraft.common.lib.events.EventHandlerEntity@62cf94b3 livingTick(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 9: ASM: vazkii.botania.common.brew.potion.PotionSoulCross@79710421 onEntityKill(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 10: ASM: cofh.core.Proxy@6143fa41 onLivingDeathEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 11: ASM: jds.bibliocraft.EventDeathDrop@6ad650bd onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 12: ASM: com.valentin4311.candycraftmod.EventCatcher@3038af2c onDeath2(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 13: ASM: noppes.npcs.ServerEventsHandler@21b12584 invoke(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 14: ASM: tconstruct.armor.player.TPlayerHandler@27b43b82 playerDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 15: ASM: micdoodle8.mods.galacticraft.planets.mars.EventHandlerMars@eb73c11 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 16: ASM: chylex.hee.system.achievements.AchievementEvents@7b48fd3e onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 17: ASM: morph.common.core.EventHandler@741908f1 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 18: ASM: lumien.randomthings.Handler.RTEventHandler@1c202179 entityDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 19: ASM: twilightforest.TFEventListener@707a1066 livingDies(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 20: ASM: tterrag.customthings.common.handlers.AchievementHandler@1dbda820 onEntityDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 21: ASM: tterrag.core.common.handlers.XPBoostHandler@74860a17 handleEntityKill(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 22: ASM: deathcounter.core.DeathCounter@59fccefd onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 23: ASM: com.rwtema.extrautils.EventHandlerServer@10a9641e ActivationRitual(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 24: ASM: com.rwtema.extrautils.EventHandlerSiege@659f6eed golemDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 25: ASM: com.rwtema.extrautils.EventHandlerSiege@659f6eed SiegeDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 26: ASM: fox.spiteful.forbidden.FMEventHandler@2d1ab32a onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 27: ASM: tombenpotter.sanguimancy.util.EventHandler@7004be65 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 28: ASM: eureka.core.EventHandler$Forge@3e00746b onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 29: ASM: tconstruct.achievements.AchievementEvents@6f21830c entitySlain(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 30: ASM: com.emoniph.witchery.item.ItemWitchHand$EventHooks@79f2dbe4 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 31: ASM: com.emoniph.witchery.blocks.BlockAreaMarker$AreaMarkerEventHooks@4d845731 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 32: ASM: com.emoniph.witchery.common.GenericEvents@1feb1270 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 33: LOW
[18:35:03] [Server thread/ERROR]: 34: ASM: com.emoniph.witchery.brewing.potions.WitcheryPotions$EventHooks@1793e100 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/ERROR]: 35: LOWEST
[18:35:03] [Server thread/ERROR]: 36: ASM: chylex.hee.mechanics.energy.EnergyEvents@63d6ea1 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
[18:35:03] [Server thread/WARN]: Failed to handle packet for /98.199.135.45:64630
java.lang.NullPointerException
    at tterrag.customthings.common.config.json.AchievementType$AchievementSource$4.matchesObject(AchievementType.java:111) ~[AchievementType$AchievementSource$4.class:?]
    at tterrag.customthings.common.handlers.AchievementHandler.onEntityDeath(AchievementHandler.java:48) ~[AchievementHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_627_AchievementHandler_onEntityDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
    at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:315) ~[ForgeHooks.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
    at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:521) ~[mw.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:979) ~[sv.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1144) ~[yz.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:646) ~[mw.class:?]
    at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:74) ~[GCEntityPlayerMP.class:?]
    at tconstruct.library.tools.AbilityHelper.onLeftClickEntity(AbilityHelper.java:125) ~[AbilityHelper.class:?]
    at tconstruct.library.tools.AbilityHelper.onLeftClickEntity(AbilityHelper.java:56) ~[AbilityHelper.class:?]
    at tconstruct.items.tools.Cleaver.onLeftClickEntity(Cleaver.java:123) ~[Cleaver.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1346) ~[yz.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1589) ~[nh.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) ~[ja.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) ~[ja.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
[18:35:03] [Server thread/INFO]: yoshiquest01 lost connection: Internal server error
[18:35:03] [Server thread/INFO]: yoshiquest01 left the game.
[18:35:08] [Server thread/INFO]: On Request: Sending WorldID packet to: prerequisite
[18:35:08] [Server thread/INFO]: prerequisite issued server command: /we cui
[18:35:08] [Thread-4109/INFO]: Login: Sending WorldID Packet to prerequisite
```

**Comment by downslope7** [comment]
Let me know if there's any other info that would be useful.

Here are the contents of customAchievements.json:

```
{"data":
  [
    {
      "name": "happyNuts",
      "page": "Squirrel-chievements",
      "source": "ITEM_PICKUP",
      "required": "customthings:item;0",
      "displayItem": "customthings:item;0"
    },
    {
      "name": "sadNuts",
      "page": "Squirrel-chievements",
      "parent": "happyNuts",
      "source": "ENTITY_KILL",
      "required": "Squirrel",
      "displayItem": "MineFactoryReloaded:fertilizer;0",
      "x": 2
    },
    {
      "name": "breakNuts",
      "page": "Squirrel-chievements",
      "parent": "happyNuts",
      "source": "BLOCK_BREAK",
      "required": "customthings:block0;0",
      "displayItem": "customthings:block0;0",
      "x": 2,
      "y": 2
    }
  ]
}
```

**Comment by tterrag1098** [comment]
Fixed via https://github.com/tterrag1098/CustomThings/commit/6e60d6ec6f7457907cc758ea4ec4aaaf73b26d87
