### ISSUE TITLE
Crash when loading with versions 10-0.0.3-34 and 10-0.0.3-33

### ISSUE THREAD

**Issue by hadn69** [tterrag1098/CustomThings#10]
```
java.lang.IllegalArgumentException: foodBottlewater is not a vaild string. Strings should be either an oredict name, or in the format objectname;damage (damage is optional)
    at com.enderio.core.common.util.ItemUtil.parseStringIntoRecipeItem(ItemUtil.java:102)
    at tterrag.customthings.common.config.json.crafting.ShapelessJsonRecipe.createRecipe(ShapelessJsonRecipe.java:33)
    at tterrag.customthings.common.config.json.crafting.ShapelessJsonRecipe.register(ShapelessJsonRecipe.java:42)
    at tterrag.customthings.common.config.ConfigHandler.addAll(ConfigHandler.java:203)
    at tterrag.customthings.common.config.ConfigHandler.postInit(ConfigHandler.java:183)
    at tterrag.customthings.CustomThings.postInit(CustomThings.java:52)
```

Here is a link to the full [crash log.](https://gist.github.com/hadn69/c7edd5cb10b629d8ddbf) I have only tried with the two versions mentioned above.

**Comment by SnowShock35** [comment]
> java.lang.IllegalArgumentException: foodBottlewater is not a vaild string. Strings should be either an oredict name, or in the format objectname;damage (damage is optional) > - @hadn69 you should read ;)

**Comment by hadn69** [comment]
I do read and that crash log is with no custom items loading.

**Comment by jaredlll08** [comment]
We need the jsons.

**Comment by tterrag1098** [comment]
The error is from your shapeless recipes file. Post that file on gist or pastebin and then give it to us.

**Comment by hadn69** [comment]
Issue was solved by regenerating the configs again.
